In [1]:
import numpy as np
import pandas as pd

# add the src folder to the path
import sys
sys.path.append('../')

from src.search import grid_search, grid_search_cv
from src.utils import load_moons, load_cup, load_monk1
from src.network import Network
from src.activations import ReLU, Tanh, Sigmoid
from src.losses import MeanSquaredError
from src.metrics import BinaryAccuracy,  MeanEuclideanError

from sklearn.metrics import accuracy_score

model = Network(9)
model.add_layer(2, ReLU())
model.add_layer(2, Sigmoid())



In [3]:
X, y, scaler = load_cup(validation=False, scale_outputs=True)
y

array([[[0.88921196],
        [0.3676885 ]],

       [[0.74337106],
        [0.29578539]],

       [[0.36630619],
        [0.20784845]],

       ...,

       [[0.39385832],
        [0.18203218]],

       [[0.10539795],
        [0.58269516]],

       [[0.72450877],
        [0.29270614]]])

In [4]:
outs= model.multiple_outputs(X)
outs.shape = outs.shape[0], outs.shape[1], 
outs.shape

(1194, 2)

In [14]:
scaler.inverse_transform(outs)

array([[ 13.26127528, -24.55803587],
       [ 13.26127528, -24.55803587],
       [ 13.26129248, -24.55998938],
       ...,
       [ 13.26137195, -24.56901837],
       [ 13.23917269, -24.54734039],
       [ 13.26127528, -24.55803587]])

array([[ 13.30845806, -24.58734245]])

In [5]:
grid_search_cv(model, X, y, metric=MeanEuclideanError(), loss=MeanSquaredError(), eta=(1e-2,), nesterov=(0.8,), reg_type=(None,), reg_val=(0,), epochs=1000, scaler=scaler)

eta= 0.01 nesterov= 0.8 reg  None lambda = 0


Training: 100%|██████████| 1000/1000[, loss=0.00658, val_loss=0.00731, val_acc=0.103]


Early stopping


Training:   0%|          | 0/1000[]


[{'parameters': (0.01, 0.8, None, 0),
  'metrics': {'accuracies': 2.036946035083529,
   'losses': 0.0068013137277685674,
   'val_losses': 2.7406921202588492}}]